"""Self-contained HTML reports for experiments.

:func:`experiment_report` renders one HTML file with no external resources
and no JavaScript: provenance, scenario definitions, summaries with
confidence intervals, a chart per metric (inline SVG), comparisons against
the baseline (with multiple-comparison adjustment), errors and a reporting
checklist. All text from the result is HTML-escaped.

>>> # result.report("report.html")  or  simulsi report results/ -o report.html
"""

from __future__ import annotations

import html
import math
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

from simulsi._version import __version__
from simulsi.analysis.report import fmt_value, html_table

if TYPE_CHECKING:
    from simulsi.experiments.experiment import ExperimentResult

_CSS = """
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#0f172a;
max-width:1100px;margin:2rem auto;padding:0 1rem;line-height:1.45}
h1{font-size:1.6rem;margin-bottom:.2rem}h2{font-size:1.2rem;margin-top:2rem;
border-bottom:1px solid #e2e8f0;padding-bottom:.3rem}h3{font-size:1rem;margin:1.2rem 0 .3rem}
.muted{color:#64748b;font-size:.9rem}table.simulsi{border-collapse:collapse;font-size:.85rem;
margin:.5rem 0}table.simulsi th,table.simulsi td{border-bottom:1px solid #e2e8f0;
padding:.25rem .6rem;text-align:left}table.simulsi th{background:#f8fafc}
caption{text-align:left;font-weight:600;padding:.3rem 0}.warn{background:#fef3c7;
padding:.5rem .8rem;border-radius:6px}.grid{display:grid;grid-template-columns:repeat(auto-fill,
minmax(480px,1fr));gap:1rem}figure{margin:0}figcaption{font-size:.85rem;font-weight:600}
"""

_COLORS = ("#4f46e5", "#0891b2", "#d97706", "#db2777", "#16a34a", "#7c3aed", "#dc2626")


def _esc(x: Any) -> str:
    return html.escape(str(x))


def _ci_chart(rows: Sequence[dict[str, Any]], metric: str) -> str:
    """Horizontal bars of scenario means with CI whiskers (inline SVG)."""
    vals = [
        v
        for r in rows
        for v in (r["mean"], r["ci_low"], r["ci_high"])
        if isinstance(v, float) and math.isfinite(v)
    ]
    if not vals:
        return ""
    lo, hi = min(0.0, *vals), max(0.0, *vals)
    if hi == lo:
        hi = lo + 1
    width, left, right, row_h = 480, 170, 20, 24
    height = 24 + row_h * len(rows)

    def x(v: float) -> float:
        return left + (v - lo) / (hi - lo) * (width - left - right)

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'width="100%" role="img" aria-label="{_esc(metric)}">',
        f'<line x1="{x(0):.1f}" x2="{x(0):.1f}" y1="4" y2="{height - 18}" stroke="#94a3b8"/>',
    ]
    for i, r in enumerate(rows):
        y = 6 + i * row_h
        mean = r["mean"]
        label = _esc(r["scenario"])[:28]
        parts.append(
            f'<text x="{left - 6}" y="{y + 13}" font-size="11" text-anchor="end">{label}</text>'
        )
        if not (isinstance(mean, float) and math.isfinite(mean)):
            continue
        x0, x1 = sorted((x(0), x(mean)))
        parts.append(
            f'<rect x="{x0:.1f}" y="{y + 2}" width="{max(x1 - x0, 1):.1f}" height="{row_h - 10}" '
            f'fill="{_COLORS[i % len(_COLORS)]}" opacity="0.75"/>'
        )
        cl, ch = r["ci_low"], r["ci_high"]
        if all(isinstance(v, float) and math.isfinite(v) for v in (cl, ch)):
            yc = y + 2 + (row_h - 10) / 2
            parts.append(
                f'<path d="M{x(cl):.1f},{yc - 5}v10M{x(cl):.1f},{yc}H{x(ch):.1f}'
                f'M{x(ch):.1f},{yc - 5}v10" stroke="#0f172a" fill="none"/>'
            )
    parts.append(
        f'<text x="{left}" y="{height - 4}" font-size="10" fill="#64748b">{fmt_value(lo)}</text>'
        f'<text x="{width - right}" y="{height - 4}" font-size="10" fill="#64748b" '
        f'text-anchor="end">{fmt_value(hi)}</text></svg>'
    )
    return "".join(parts)


def experiment_report(
    result: ExperimentResult,
    *,
    metrics: Sequence[str] | None = None,
    baseline: str | None = None,
    confidence: float = 0.95,
    adjust: str = "holm",
    title: str | None = None,
    max_metrics: int = 24,
) -> str:
    """Render ``result`` as a standalone HTML document (returned as a string)."""
    md = result.metadata
    names = list(metrics) if metrics is not None else _default_metrics(result, max_metrics)
    scenarios = result.scenarios
    summary = result.summary(names, confidence=confidence)
    title = title or f"{md.name} - SimulSI experiment report"
    out = [
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width,initial-scale=1'>",
        f"<title>{_esc(title)}</title><style>{_CSS}</style></head><body>",
        f"<h1>{_esc(title)}</h1>",
        f"<p class='muted'>Generated by SimulSI {_esc(__version__)} from experiment "
        f"{_esc(md.experiment_id)} ({_esc(md.timestamp)}).</p>",
        "<h2>Provenance</h2>",
    ]
    git = md.git or {}
    env = md.environment or {}
    prov: list[dict[str, Any]] = [
        {"item": "model", "value": f"{md.model_name} (version {md.model_version})"},
        {"item": "replications per scenario", "value": md.replications},
        {"item": "seed", "value": md.seed},
        {"item": "common random numbers", "value": md.common_random_numbers},
        {"item": "antithetic pairs", "value": md.antithetic},
        {"item": "run length", "value": "model default" if md.duration is None else md.duration},
        {"item": "warm-up", "value": md.warmup},
        {
            "item": "git commit",
            "value": f"{git.get('commit') or '-'}"
            + (" (uncommitted changes)" if git.get("dirty") else ""),
        },
        {
            "item": "python / simulsi",
            "value": f"{env.get('python', '-')} / {env.get('simulsi', __version__)}",
        },
        {"item": "runtime (s)", "value": round(md.runtime, 3)},
    ]
    if md.stopping:
        prov.append({"item": "stopping rule", "value": str(md.stopping)})
    out.append(html_table(prov))
    out.append("<h2>Scenarios</h2>")
    params = sorted({k for sc in scenarios for k in md.scenarios.get(sc, {})})
    out.append(
        html_table(
            [{"scenario": sc, **md.scenarios.get(sc, {})} for sc in scenarios],
            ["scenario", *params],
        )
    )
    if result.errors:
        out.append(
            f"<p class='warn'>{len(result.errors)} replication(s) failed and are excluded; "
            f"first error: {_esc(result.errors[0].error)}</p>"
        )
    out.append(f"<h2>Results ({confidence:.0%} confidence intervals)</h2>")
    out.append(html_table(summary, ["scenario", "metric", "n", "mean", "ci_low", "ci_high", "std"]))
    out.append("<div class='grid'>")
    for m in names:
        rows = [r for r in summary if r["metric"] == m]
        chart = _ci_chart(rows, m)
        if chart:
            out.append(f"<figure><figcaption>{_esc(m)}</figcaption>{chart}</figure>")
    out.append("</div>")
    if len(scenarios) > 1:
        base = baseline if baseline is not None else scenarios[0]
        cmp = result.compare(base, metrics=names, confidence=confidence, adjust=adjust)
        out.append(f"<h2>Differences from {_esc(base)}</h2>")
        out.append(
            "<p class='muted'>Paired-t intervals with common random numbers, otherwise "
            f"Welch; p-values adjusted with {_esc(adjust)}.</p>"
        )
        out.append(
            html_table(
                cmp.to_dicts(),
                [
                    "metric",
                    "scenario",
                    "absolute_difference",
                    "percentage_difference",
                    "ci_low",
                    "ci_high",
                    "p_value",
                    "p_adjusted",
                    "significant",
                ],
            )
        )
    out += [
        "<h2>Before you report these numbers</h2><ul>",
        "<li>Intervals cover simulation sampling error only, not model error.</li>",
        "<li>State how run length, warm-up and the number of replications were chosen.</li>",
        "<li>Describe the validation performed and its limits.</li>",
        "<li>Many comparisons inflate false positives; prefer adjusted p-values.</li>",
        "</ul></body></html>",
    ]
    return "\n".join(out)


def _default_metrics(result: ExperimentResult, limit: int) -> list[str]:
    preferred = [
        m
        for m in result.metric_names
        if not m.startswith("sim.") and not m.endswith((".min", ".max", ".rate"))
    ]
    return (preferred or result.metric_names)[:limit]


def write_report(html_text: str, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(html_text, encoding="utf-8")
    return p
